ALTER TABLE "Sucursal"
  ADD COLUMN "deliveryEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "deliveryRadiusKm" DOUBLE PRECISION NOT NULL DEFAULT 14,
  ADD COLUMN "deliverySlots" TEXT[] NOT NULL DEFAULT ARRAY['08-12', '17-20']::TEXT[],
  ADD COLUMN "freeShippingDays" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[];